### ISSUE TITLE
[BUG?] Blocking all traffic after some time

### ISSUE THREAD

**Issue by weisJ** [ProxymanApp/Tiny-Shield#39]
A of lately I noticed that after some time of the app running all internet traffic would be blocked (usually after waking up from sleep). In this case only restarting macOS would help. Now I am not 100% certain that it is the fault of Tiny-Shield, as disabling the network extension requires a restart, which would fix it anyway. However I have been running with Tiny-Shield turned off now for a few days and it never happened again, which leads me to suspect that it might be related to this application.

I know this is very vague, so if there is any additional information that I can provide please let me know.

**Comment by kics223w1** [comment]
Thank you for the detailed report! 🙏  
I'll try to reproduce the issue on my end and investigate further.

Just a quick question: Are you currently using Tiny Shield alongside any other network monitoring or tracking tools? 🤔

Also, as a side note, there's no need to restart your Mac to disable the Network Extension.  You can simply remove it in the System Settings.

<img width="1682" alt="Image" src="https://github.com/user-attachments/assets/e35da1c6-0208-4cec-bed4-fa74c3a6f4fb" />

**Comment by NghiaTranUIT** [comment]
@weisJ if you don't mind, please update to the latest version v0.6.0. We fixed some issues that might cause the crash and block your Internet Connection.

It also includes the Sentry, so we can check the Crash Log too

**Comment by weisJ** [comment]
Disabling the extension did not resolve the issue when it happened - I assumed the restart was necessary, as macOS warns this might be the case when disabling.

Will update and report back :)

**Comment by NghiaTranUIT** [comment]
thanks, if you encounter the issue again, please open Console App -> Filter with `com.proxyman.ProxymanGuard.NetworkExtension` and share with me the result. Maybe you can export it.

It will contain the hint why Network Extension is failed. Thanks in advance.

**Comment by kics223w1** [comment]
If the issue occurs again, please run the command below and share with us the file.  It’s an additional way to capture the Network Extension logs.
``` sh
log stream \
  --predicate 'process == "com.proxyman.ProxymanGuard.NetworkExtension"' \
  --info \
  --debug \
  --style compact \
| tee -a ~/Desktop/TinyShield.log
```

**Comment by NghiaTranUIT** [comment]
@weisJ let;'s try this Beta build: https://github.com/ProxymanApp/Tiny-Shield/releases/tag/0.6.1

We fixed it 👍

**Comment by weisJ** [comment]
Just wanted to report back, that using the new version I have not since experienced the issue again 👍🏼

**Comment by NghiaTranUIT** [comment]
Awesome, thanks your report 👍
